<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiswaSeeder extends Seeder
{
    public function run()
    {
        DB::table('tb_siswa')->insert([
            [
                'nis' => 3177549474,
                'nisn' => 3177549474,
                'nama' => 'ADINDA DILA AZKADINA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-12-08',
                'jk' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'EFENDI',
                'nama_ibu' => 'SHELA SARIYANI',
            ],
            [
                'nis' => 3176779014,
                'nisn' => 3176779014,
                'nama' => 'GEDE ARGATA WIBISANA INDRAWAN',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'tanggal_lahir' => '2017-10-10',
                'jk' => 'Laki-Laki',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'MADE INDRAWAN',
                'nama_ibu' => 'KADEK FEBRIANI',
            ],
            [
                'nis' => 3186310274,
                'nisn' => 3186310274,
                'nama' => 'GUSTI AYU SARAS DWI MOZA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2018-03-17',
                'jk' => 'Perempuan',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'GUSTI NGURAH SUSANA',
                'nama_ibu' => 'MADE WILASMINI',
            ],
            [
                'nis' => 3171781425,
                'nisn' => 3171781425,
                'nama' => 'GUSTI AYUTU PUTRI RENITA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-12-31',
                'jk' => 'Perempuan',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'GUSTI PUTU MARE',
                'nama_ibu' => 'GUSTI NGURAH SUPARDESI',
            ],
            [
                'nis' => 3189969809,
                'nisn' => 3189969809,
                'nama' => 'GUSTI KOMANG SURIARSE',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2018-04-14',
                'jk' => 'Laki-Laki',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'GUSTI NGURAH SURATNYE',
                'nama_ibu' => 'JRO KETUT PARMI',
            ],
            [
                'nis' => 3171104153,
                'nisn' => 3171104153,
                'nama' => 'HASNA ARSILA AQILA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-11-04',
                'jk' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'ISMAIL',
                'nama_ibu' => 'JUBAIDAH',
            ],
            [
                'nis' => 3171661009,
                'nisn' => 3171661009,
                'nama' => 'I MADE RENDRA ADINATA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-11-11',
                'jk' => 'Laki-Laki',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'KETUT DARMAYANA',
                'nama_ibu' => 'PUTU EKA FITRIA',
            ],
            [
                'nis' => 3171593829,
                'nisn' => 3171593829,
                'nama' => 'I PUTU MONDY SKYRAINDRA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-10-16',
                'jk' => 'Laki-Laki',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'WAYAN SUKRAWAN',
                'nama_ibu' => 'MADE DWI PURNAMI',
            ],
            [
                'nis' => 3177473095,
                'nisn' => 3177473095,
                'nama' => 'KADEK WIRA SATRIAWAN',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-03-05',
                'jk' => 'Laki-Laki',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'NYOMAN BUDARTE',
                'nama_ibu' => 'ILUH WATEK AYU',
            ],
            [
                'nis' => 3171465031,
                'nisn' => 3171465031,
                'nama' => 'KETUT NADYA SWARA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-11-22',
                'jk' => 'Perempuan',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'WAYAN PANDE',
                'nama_ibu' => 'NI KADEK SUARNITA',
            ],
            [
                'nis' => 3178018178,
                'nisn' => 3178018178,
                'nama' => 'KOMANG SEPTIA RANI',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-09-20',
                'jk' => 'Perempuan',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'KADEK TASTRE',
                'nama_ibu' => 'PUTU KARTINI',
            ],
            [
                'nis' => 3182206155,
                'nisn' => 3182206155,
                'nama' => 'KOMANG SUANDITA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2018-07-21',
                'jk' => 'Laki-Laki',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'NYOMAN ARTIKA',
                'nama_ibu' => 'DESAK MADE JULIANTINI',
            ],
        ]);
    }
}
