<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiswaSeeder extends Seeder
{
    public function run()
    {
        DB::table('tb_siswa')->insert([
            [
                'nis' => 3177549474,
                'nisn' => 3177549474,
                'nama' => 'ADINDA DILA AZKADINA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-12-08',
                'jk' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'EFENDI',
                'nama_ibu' => 'SHELA SARIYANI',
            ],
            [
                'nis' => 3176779014,
                'nisn' => 3176779014,
                'nama' => 'GEDE ARGATA WIBISANA INDRAWAN',
                'tempat_lahir' => 'BANDAR LAMPUNG',
                'tanggal_lahir' => '2017-10-10',
                'jk' => 'Laki-Laki',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'MADE INDRAWAN',
                'nama_ibu' => 'KADEK FEBRIANI',
            ],
            [
                'nis' => 3186310274,
                'nisn' => 3186310274,
                'nama' => 'GUSTI AYU SARAS DWI MOZA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2018-03-17',
                'jk' => 'Perempuan',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'GUSTI NGURAH SUSANA',
                'nama_ibu' => 'MADE WILASMINI',
            ],
            [
                'nis' => 3171781425,
                'nisn' => 3171781425,
                'nama' => 'GUSTI AYUTU PUTRI RENITA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-12-31',
                'jk' => 'Perempuan',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'GUSTI PUTU MARE',
                'nama_ibu' => 'GUSTI NGURAH SUPARDESI',
            ],
            [
                'nis' => 3189969809,
                'nisn' => 3189969809,
                'nama' => 'GUSTI KOMANG SURIARSE',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2018-04-14',
                'jk' => 'Laki-Laki',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'GUSTI NGURAH SURATNYE',
                'nama_ibu' => 'JRO KETUT PARMI',
            ],
            [
                'nis' => 3171104153,
                'nisn' => 3171104153,
                'nama' => 'HASNA ARSILA AQILA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-11-04',
                'jk' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'ISMAIL',
                'nama_ibu' => 'JUBAIDAH',
            ],
            [
                'nis' => 3171661009,
                'nisn' => 3171661009,
                'nama' => 'I MADE RENDRA ADINATA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-11-11',
                'jk' => 'Laki-Laki',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'KETUT DARMAYANA',
                'nama_ibu' => 'PUTU EKA FITRIA',
            ],
            [
                'nis' => 3171593829,
                'nisn' => 3171593829,
                'nama' => 'I PUTU MONDY SKYRAINDRA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-10-16',
                'jk' => 'Laki-Laki',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'WAYAN SUKRAWAN',
                'nama_ibu' => 'MADE DWI PURNAMI',
            ],
            [
                'nis' => 3177473095,
                'nisn' => 3177473095,
                'nama' => 'KADEK WIRA SATRIAWAN',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-03-05',
                'jk' => 'Laki-Laki',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'NYOMAN BUDARTE',
                'nama_ibu' => 'ILUH WATEK AYU',
            ],
            [
                'nis' => 3171465031,
                'nisn' => 3171465031,
                'nama' => 'KETUT NADYA SWARA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-11-22',
                'jk' => 'Perempuan',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'WAYAN PANDE',
                'nama_ibu' => 'NI KADEK SUARNITA',
            ],
            [
                'nis' => 3182149602,
                'nisn' => 3182149602,
                'nama' => 'KETUT ZHIA BARAT WAJE',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2018-07-08',
                'jk' => 'Perempuan',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'MADE KONDE',
                'nama_ibu' => 'NYOMAN SURINI',
            ],
            [
                'nis' => 3178018178,
                'nisn' => 3178018178,
                'nama' => 'KOMANG SEPTIA RANI',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-09-20',
                'jk' => 'Perempuan',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'KADEK TASTRE',
                'nama_ibu' => 'PUTU KARTINI',
            ],
            [
                'nis' => 3182206155,
                'nisn' => 3182206155,
                'nama' => 'KOMANG SUANDITA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2018-07-21',
                'jk' => 'Laki-Laki',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'NYOMAN ARTIKA',
                'nama_ibu' => 'DESAK MADE JULIANTINI',
            ],
            [
                'nis' => 3168200641,
                'nisn' => 3168200641,
                'nama' => 'MADE NOVA ADNYANA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2016-11-16',
                'jk' => 'Laki-Laki',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'MADE SUARNE',
                'nama_ibu' => 'ILUH SARIANI',
            ],
            [
                'nis' => 3188073477,
                'nisn' => 3188073477,
                'nama' => 'MADE SUCIANI',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2018-03-25',
                'jk' => 'Perempuan',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'MADE MINGGU',
                'nama_ibu' => 'KOMANG WERESTINI',
            ],
            [
                'nis' => 3183663568,
                'nisn' => 3183663568,
                'nama' => 'MUHAMMAD IBNU AQIL',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2018-06-11',
                'jk' => 'Laki-Laki',
                'agama' => 'Islam',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'ADENAN',
                'nama_ibu' => 'YULIYANTI',
            ],
            [
                'nis' => 3183792890,
                'nisn' => 3183792890,
                'nama' => 'MUHAMMAD NAZRIEL AL HAFIZ',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2018-04-26',
                'jk' => 'Laki-Laki',
                'agama' => 'Islam',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'SUHARI',
                'nama_ibu' => 'TITIN',
            ],
            [
                'nis' => 3179607201,
                'nisn' => 3179607201,
                'nama' => 'NESIA ZULAIKHA ALMEVIRA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-03-31',
                'jk' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'JONI BASNI',
                'nama_ibu' => 'SRI AGUS TINA',
            ],
            [
                'nis' => 3175291615,
                'nisn' => 3175291615,
                'nama' => 'NI KETUT AYU SEKAR ASIH',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-07-28',
                'jk' => 'Perempuan',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'KADEK RUPASA',
                'nama_ibu' => 'NYOMAN SARYATI',
            ],
            [
                'nis' => 3175947653,
                'nisn' => 3175947653,
                'nama' => 'NYOMAN FABYOLA ARSYISYLA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-06-30',
                'jk' => 'Perempuan',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'GEDE SIBANG ARNAWE',
                'nama_ibu' => 'SRI LESTARI',
            ],
            [
                'nis' => 3175642277,
                'nisn' => 3175642277,
                'nama' => 'NYOMAN GAURI WIPATRI',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-11-12',
                'jk' => 'Perempuan',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'WAYAN PASEK DARME',
                'nama_ibu' => 'WIWIN REPIANA',
            ],
            [
                'nis' => 3184046133,
                'nisn' => 3184046133,
                'nama' => 'PUTU AYU FEBRI NINGSIH',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2018-02-22',
                'jk' => 'Perempuan',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'KETUT SETIASE',
                'nama_ibu' => 'MADE SADIASIH',
            ],
            [
                'nis' => 3178703346,
                'nisn' => 3178703346,
                'nama' => 'QIANDRA RAHENA DEA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-12-15',
                'jk' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'KHOLIS HIDAYAT',
                'nama_ibu' => 'RINDRIA APRIANI',
            ],
            [
                'nis' => 3174302279,
                'nisn' => 3174302279,
                'nama' => 'YUGE HRSIKESA',
                'tempat_lahir' => 'OKU TIMUR',
                'tanggal_lahir' => '2017-12-08',
                'jk' => 'Laki-Laki',
                'agama' => 'Hindu',
                'alamat' => 'NUSABALI',
                'nama_ayah' => 'KOMANG SUKRE SARIASE',
                'nama_ibu' => 'NYOMAN SEMANI',
            ]
        ]);
    }
}
